service: janelia-neuronbridge-website

plugins:
  - serverless-finch
  - serverless-plugin-package-json

custom:
  stage: ${opt:stage, self:provider.stage}
  region : ${opt:region, self:provider.region}
  client:
    bucketName: janelia-neuronbridge-web-${self:custom.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: max-age=0
    tags:
      PROJECT: neuronbridge
      DEVELOPER: ${env:USER}
      VERSION: ${pkgjson:version}

provider:
  name: aws
  region: us-east-1
  stage: dev
