service: janelia-neuronbridge-web

plugins:
  - serverless-finch
  - serverless-plugin-package-json
  - serverless-deployment-bucket

custom:
  stage: ${opt:stage, self:provider.stage}
  region : ${opt:region, self:provider.region}
  client:
    bucketName: ${self:service}-${self:custom.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: max-age=0

provider:
  name: aws
  region: us-east-1
  stage: dev
  deploymentBucket:
    name: janelia-serverless-deployments
    blockPublicAccess: true

resources:
  - ${file(resources/buckets.yml)}
  - ${file(resources/cognito-pools.yml)}
