Resources:

  CognitoUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: ${self:service}-user-pool-${self:custom.stage}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: neuronbridge-${self:custom.stage}
      UserPoolId:
        Ref: CognitoUserPool

  CognitoUserPoolGroupAdmin:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Administrative users for Neuronbridge
      GroupName: neuronbridge-admins
      Precedence: 0
      RoleArn: arn:aws:iam::777794738451:role/NeuronBridge_AdminRole
      UserPoolId:
        Ref: CognitoUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:service}-${self:custom.stage}-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - https://neuronbridge-dev.janelia.org:3000
        - https://neuronbridge.janelia.org
      LogoutURLs:
        - https://neuronbridge-dev.janelia.org:3000
        - https://neuronbridge.janelia.org
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
        - Google
    DependsOn:
      - GoogleUserPoolIdentityProvider

  GoogleUserPoolIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId:
        Ref: CognitoUserPool
      ProviderName: Google
      ProviderDetails:
        client_id: "{{resolve:secretsmanager:neuronbridge_google_id_provider:SecretString:appID}}"
        client_secret: "{{resolve:secretsmanager:neuronbridge_google_id_provider:SecretString:appSecret}}"
        authorize_scopes: profile email openid
      ProviderType: Google
      AttributeMapping:
        email: email
        email_verified: email_verified
        username: sub

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
    # Generate a name based on the stage
      IdentityPoolName: ${self:service}-${self:custom.stage}-id-pool
      # Don't allow unathenticated users
      AllowUnauthenticatedIdentities: false
      # Link to our User Pool
      CognitoIdentityProviders:
        - ClientId:
            Ref: CognitoUserPoolClient
          ProviderName:
            Fn::GetAtt: [ "CognitoUserPool", "ProviderName" ]

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: CognitoIdentityPool
      Roles:
        authenticated:
          Fn::GetAtt: [CognitoAuthRole, Arn]
        unauthenticated:
          Fn::GetAtt: [CognitoUnAuthRole, Arn]

  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: 'NeuronBridge_Download'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectTagging"
                Resource:
                  - arn:aws:s3:::janelia-neuronbridge-download-${self:custom.stage}/*
        - PolicyName: 'NeuronBridge_Private'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectTagging"
                  - "s3:DeleteObject"
                  - "s3:GetObject"
                  - "s3:GetObjectTagging"
                Resource:
                  - Fn::Join:
                    - ''
                    -
                      - arn:aws:s3:::janelia-neuronbridge-searches-${self:custom.stage}
                      - '/private/'
                      - '$'
                      - '{cognito-identity.amazonaws.com:sub}/*'
        - PolicyName: 'NeuronBridge_Protected'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectTagging"
                  - "s3:DeleteObject"
                  - "s3:GetObject"
                  - "s3:GetObjectTagging"
                Resource:
                  - Fn::Join:
                    - ''
                    -
                      - arn:aws:s3:::janelia-neuronbridge-searches-${self:custom.stage}
                      - '/protected/'
                      - '$'
                      - '{cognito-identity.amazonaws.com:sub}/*'
        - PolicyName: 'NeuronBridge_Read'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - "s3:GetObject"
                Resource:
                  - Fn::Join:
                    - ''
                    -
                      - arn:aws:s3:::janelia-neuronbridge-searches-${self:custom.stage}
                      - '/protected/*'
              - Effect: 'Allow'
                Condition:
                  StringLike:
                    s3:prefix:
                      - "public/"
                      - "public/*"
                      - "protected/"
                      - "protected/*"
                      - Fn::Join:
                        - ''
                        -
                          - "private/$"
                          - "{cognito-identity.amazonaws.com:sub}/"
                      - Fn::Join:
                        - ''
                        -
                          - "private/$"
                          - "{cognito-identity.amazonaws.com:sub}/*"

                Action:
                  - "s3:ListBucket"
                Resource:
                  - arn:aws:s3:::janelia-neuronbridge-searches-${self:custom.stage}

  CognitoAdminRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: 'NeuronBridgeAdminAllAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectTagging"
                  - "s3:GetObject"
                  - "s3:GetObjectTagging"
                  - "s3:DeleteObject"
                Resource:
                  - arn:aws:s3:::janelia-neuronbridge-searches-${self:custom.stage}/*
                  - arn:aws:s3:::janelia-neuronbridge-downloads-${self:custom.stage}/*
              - Effect: 'Allow'
                Action:
                  - "s3:ListBucket"
                Resource:
                  - arn:aws:s3:::janelia-neuronbridge-searches-${self:custom.stage}
                  - arn:aws:s3:::janelia-neuronbridge-downloads-${self:custom.stage}

  CognitoUnAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
  IdentityPoolId:
    Value:
      Ref: CognitoIdentityPool


